{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-12T23:32:23+03:00","message":"GetUser: failed to execute query"}
{"level":"error","module":"service","error":"rpc error: code = Internal desc = Internal server error","time":"2025-02-12T23:32:23+03:00","message":"failed to get user from storage"}
{"level":"error","module":"api","error":"rpc error: code = Internal desc = Internal server error","time":"2025-02-12T23:32:23+03:00","message":"failed to auth user"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-12T23:35:56+03:00","message":"GetUser: failed to execute query"}
{"level":"error","module":"service","error":"rpc error: code = Internal desc = Internal server error","time":"2025-02-12T23:35:56+03:00","message":"failed to get user from storage"}
{"level":"error","module":"api","error":"rpc error: code = Internal desc = Internal server error","time":"2025-02-12T23:35:56+03:00","message":"failed to auth user"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-12T23:36:04+03:00","message":"GetUser: failed to execute query"}
{"level":"error","module":"service","error":"rpc error: code = Internal desc = Internal server error","time":"2025-02-12T23:36:04+03:00","message":"failed to get user from storage"}
{"level":"error","module":"api","error":"rpc error: code = Internal desc = Internal server error","time":"2025-02-12T23:36:04+03:00","message":"failed to auth user"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-12T23:42:38+03:00","message":"GetUser: failed to execute query"}
{"level":"error","module":"service","error":"rpc error: code = Internal desc = Internal server error","time":"2025-02-12T23:42:38+03:00","message":"failed to get user from storage"}
{"level":"error","module":"api","error":"rpc error: code = Internal desc = Internal server error","time":"2025-02-12T23:42:38+03:00","message":"failed to auth user"}
{"level":"warn","module":"repository","username":"admin","time":"2025-02-12T23:46:39+03:00","message":"GetUser: user not found"}
{"level":"error","module":"repository","error":"ERROR: INSERT has more target columns than expressions (SQLSTATE 42601)","time":"2025-02-12T23:46:39+03:00","message":"CreateUser: failed to execute query"}
{"level":"error","module":"service","error":"rpc error: code = Internal desc = Internal server error","time":"2025-02-12T23:46:39+03:00","message":"failed to create new user in storage"}
{"level":"error","module":"api","error":"rpc error: code = Internal desc = Internal server error","time":"2025-02-12T23:46:39+03:00","message":"failed to auth user"}
{"level":"warn","module":"repository","username":"admin","time":"2025-02-12T23:47:08+03:00","message":"GetUser: user not found"}
{"level":"error","module":"repository","error":"ERROR: INSERT has more target columns than expressions (SQLSTATE 42601)","time":"2025-02-12T23:47:16+03:00","message":"CreateUser: failed to execute query"}
{"level":"error","module":"service","error":"rpc error: code = Internal desc = Internal server error","time":"2025-02-12T23:47:16+03:00","message":"failed to create new user in storage"}
{"level":"warn","module":"repository","username":"admin","time":"2025-02-12T23:48:11+03:00","message":"GetUser: user not found"}
{"level":"error","module":"repository","error":"ERROR: INSERT has more target columns than expressions (SQLSTATE 42601)","time":"2025-02-12T23:48:11+03:00","message":"CreateUser: failed to execute query"}
{"level":"error","module":"service","error":"rpc error: code = Internal desc = Internal server error","time":"2025-02-12T23:48:11+03:00","message":"failed to create new user in storage"}
{"level":"error","module":"api","error":"rpc error: code = Internal desc = Internal server error","time":"2025-02-12T23:48:11+03:00","message":"failed to auth user"}
{"level":"warn","module":"repository","username":"admin","time":"2025-02-12T23:48:33+03:00","message":"GetUser: user not found"}
{"level":"warn","module":"repository","username":"admin","time":"2025-02-12T23:51:08+03:00","message":"GetUser: user not found"}
{"level":"error","module":"repository","error":"number of field descriptions must equal number of destinations, got 2 and 3","time":"2025-02-12T23:51:08+03:00","message":"CreateUser: failed to execute query"}
{"level":"error","module":"service","error":"rpc error: code = Internal desc = Internal server error","time":"2025-02-12T23:51:08+03:00","message":"failed to create new user in storage"}
{"level":"error","module":"api","error":"rpc error: code = Internal desc = Internal server error","time":"2025-02-12T23:51:08+03:00","message":"failed to auth user"}
{"level":"warn","module":"repository","username":"admin1","time":"2025-02-12T23:52:19+03:00","message":"GetUser: user not found"}
{"level":"error","module":"repository","error":"number of field descriptions must equal number of destinations, got 2 and 3","time":"2025-02-12T23:52:19+03:00","message":"CreateUser: failed to execute query"}
{"level":"error","module":"service","error":"rpc error: code = Internal desc = Internal server error","time":"2025-02-12T23:52:19+03:00","message":"failed to create new user in storage"}
{"level":"error","module":"api","error":"rpc error: code = Internal desc = Internal server error","time":"2025-02-12T23:52:19+03:00","message":"failed to auth user"}
{"level":"warn","module":"repository","username":"admin2","time":"2025-02-12T23:56:30+03:00","message":"GetUser: user not found"}
{"level":"warn","module":"repository","username":"admin2","time":"2025-02-12T23:58:22+03:00","message":"GetUser: user not found"}
{"level":"warn","module":"repository","username":"admin","time":"2025-02-12T23:58:54+03:00","message":"GetUser: user not found"}
{"level":"error","module":"service","error":"crypto/bcrypt: hashedPassword is not the hash of the given password","time":"2025-02-12T23:59:00+03:00","message":"password mismatch"}
{"level":"error","module":"api","error":"crypto/bcrypt: hashedPassword is not the hash of the given password","time":"2025-02-12T23:59:00+03:00","message":"failed to auth user"}
{"level":"warn","module":"repository","username":"admi","time":"2025-02-12T23:59:06+03:00","message":"GetUser: user not found"}
{"level":"error","module":"repository","error":"unexpected EOF","time":"2025-02-13T18:47:39+03:00","message":"GetUser: failed to execute query"}
{"level":"error","module":"service","error":"rpc error: code = Internal desc = Internal server error","time":"2025-02-13T18:47:39+03:00","message":"failed to get user from storage"}
{"level":"error","module":"api","error":"rpc error: code = Internal desc = Internal server error","time":"2025-02-13T18:47:39+03:00","message":"failed to auth user"}
{"level":"warn","module":"repository","username":"admi","time":"2025-02-13T18:52:11+03:00","message":"GetUser: user not found"}
{"level":"warn","module":"repository","username":"admin","time":"2025-02-13T19:09:51+03:00","message":"GetUser: user not found"}
{"level":"warn","module":"repository","username":"user1","time":"2025-02-13T19:10:56+03:00","message":"GetUser: user not found"}
{"level":"warn","module":"repository","username":"user1","time":"2025-02-14T19:27:46+03:00","message":"GetUser: user not found"}
{"level":"warn","module":"repository","username":"user2","time":"2025-02-14T19:27:55+03:00","message":"GetUser: user not found"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-14T21:15:12+03:00","message":"BuyItem: failed to update users"}
{"level":"error","module":"service","error":"no rows in result set","time":"2025-02-14T21:15:12+03:00","message":"failed to but item books"}
{"level":"error","module":"api","error":"no rows in result set","time":"2025-02-14T21:15:12+03:00","message":"failed to buy item books"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-14T23:05:42+03:00","message":"UpdateBalanceForPurchase: failed to update users"}
{"level":"error","module":"api","error":"no rows in result set","time":"2025-02-14T23:05:42+03:00","message":"failed to buy item books"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-14T23:07:05+03:00","message":"UpdateBalanceForPurchase: failed to update users"}
{"level":"error","module":"api","error":"no rows in result set","time":"2025-02-14T23:07:05+03:00","message":"failed to buy item books"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-14T23:19:48+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"api","error":"ошибка при обновлении данных: no rows in result set","time":"2025-02-14T23:19:48+03:00","message":"failed to buy item books"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-14T23:22:21+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-14T23:26:44+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-14T23:29:21+03:00","message":"UpdateBalanceForPurchase: item books not found"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-14T23:37:32+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"ERROR: insert or update on table \"purchases\" violates foreign key constraint \"purchases_products_id_fkey\" (SQLSTATE 23503)","time":"2025-02-14T23:37:32+03:00","message":"InsertPurchaseRecord: failed to insert purchase"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-14T23:39:16+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T09:57:26+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"ERROR: table name \"users\" specified more than once (SQLSTATE 42712)","time":"2025-02-15T09:59:53+03:00","message":"UpdateSenderBalance: failed to update sender balance"}
{"level":"error","module":"repository","error":"ERROR: table name \"users\" specified more than once (SQLSTATE 42712)","time":"2025-02-15T10:05:44+03:00","message":"UpdateSenderBalance: failed to update sender balance"}
{"level":"error","module":"repository","error":"ERROR: table name \"users\" specified more than once (SQLSTATE 42712)","time":"2025-02-15T10:05:51+03:00","message":"UpdateSenderBalance: failed to update sender balance"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:09:19+03:00","message":"UpdateReceiverBalance: failed to update receiver balance"}
{"level":"error","module":"service","time":"2025-02-15T10:10:05+03:00","message":"not enough coins for transaction"}
{"level":"error","module":"service","time":"2025-02-15T10:25:58+03:00","message":"not enough coins for transaction"}
{"level":"error","module":"service","time":"2025-02-15T10:26:03+03:00","message":"not enough coins for transaction"}
{"level":"error","module":"service","time":"2025-02-15T10:26:04+03:00","message":"not enough coins for transaction"}
{"level":"error","module":"service","time":"2025-02-15T10:26:05+03:00","message":"not enough coins for transaction"}
{"level":"error","module":"service","time":"2025-02-15T10:26:08+03:00","message":"not enough coins for transaction"}
{"level":"error","module":"service","time":"2025-02-15T10:26:09+03:00","message":"not enough coins for transaction"}
{"level":"error","module":"service","time":"2025-02-15T10:26:09+03:00","message":"not enough coins for transaction"}
{"level":"error","module":"service","time":"2025-02-15T10:26:10+03:00","message":"not enough coins for transaction"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:23+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:25+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:26+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:27+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:27+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:28+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:28+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:29+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:32+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:33+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:33+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:34+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:34+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:34+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:35+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:35+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:36+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:36+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:36+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:37+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:37+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:37+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:38+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:28:38+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"ERROR: new row for relation \"users\" violates check constraint \"users_coins_check\" (SQLSTATE 23514)","time":"2025-02-15T10:37:02+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"ERROR: new row for relation \"users\" violates check constraint \"users_coins_check\" (SQLSTATE 23514)","time":"2025-02-15T10:37:03+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"ERROR: new row for relation \"users\" violates check constraint \"users_coins_check\" (SQLSTATE 23514)","time":"2025-02-15T10:40:23+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"ERROR: new row for relation \"users\" violates check constraint \"users_coins_check\" (SQLSTATE 23514)","time":"2025-02-15T10:40:24+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"ERROR: new row for relation \"users\" violates check constraint \"users_coins_check\" (SQLSTATE 23514)","time":"2025-02-15T10:40:24+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"ERROR: new row for relation \"users\" violates check constraint \"users_coins_check\" (SQLSTATE 23514)","time":"2025-02-15T10:40:25+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"ERROR: new row for relation \"users\" violates check constraint \"users_coins_check\" (SQLSTATE 23514)","time":"2025-02-15T10:40:25+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"ERROR: new row for relation \"users\" violates check constraint \"users_coins_check\" (SQLSTATE 23514)","time":"2025-02-15T10:40:25+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"ERROR: new row for relation \"users\" violates check constraint \"users_coins_check\" (SQLSTATE 23514)","time":"2025-02-15T10:40:26+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"ERROR: new row for relation \"users\" violates check constraint \"users_coins_check\" (SQLSTATE 23514)","time":"2025-02-15T10:40:26+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"ERROR: new row for relation \"users\" violates check constraint \"users_coins_check\" (SQLSTATE 23514)","time":"2025-02-15T10:40:27+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"ERROR: new row for relation \"users\" violates check constraint \"users_coins_check\" (SQLSTATE 23514)","time":"2025-02-15T10:40:27+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"ERROR: new row for relation \"users\" violates check constraint \"users_coins_check\" (SQLSTATE 23514)","time":"2025-02-15T10:40:28+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"ERROR: new row for relation \"users\" violates check constraint \"users_coins_check\" (SQLSTATE 23514)","time":"2025-02-15T10:40:28+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"ERROR: new row for relation \"users\" violates check constraint \"users_coins_check\" (SQLSTATE 23514)","time":"2025-02-15T10:40:29+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"ERROR: new row for relation \"users\" violates check constraint \"users_coins_check\" (SQLSTATE 23514)","time":"2025-02-15T10:40:29+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"ERROR: new row for relation \"users\" violates check constraint \"users_coins_check\" (SQLSTATE 23514)","time":"2025-02-15T10:40:29+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"ERROR: new row for relation \"users\" violates check constraint \"users_coins_check\" (SQLSTATE 23514)","time":"2025-02-15T10:40:30+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"no rows in result set","time":"2025-02-15T10:42:25+03:00","message":"UpdateBalanceForPurchase: failed to update user data"}
{"level":"error","module":"repository","error":"ERROR: syntax error at or near \"GROUP\" (SQLSTATE 42601)","time":"2025-02-15T12:06:25+03:00","message":"GetItemsByUserId: failed to scan rows"}
{"level":"error","module":"repository","error":"ERROR: syntax error at or near \"GROUP\" (SQLSTATE 42601)","time":"2025-02-15T12:12:31+03:00","message":"GetItemsByUserId: failed to scan rows"}
{"level":"error","module":"repository","error":"ERROR: syntax error at or near \"GROUP\" (SQLSTATE 42601)","time":"2025-02-15T12:13:18+03:00","message":"GetItemsByUserId: failed to scan rows"}
{"level":"error","module":"repository","error":"ERROR: syntax error at or near \"GROUP\" (SQLSTATE 42601)","time":"2025-02-15T12:14:47+03:00","message":"GetItemsByUserId: failed to scan rows"}
{"level":"error","module":"repository","error":"ERROR: syntax error at or near \"GROUP\" (SQLSTATE 42601)","time":"2025-02-15T12:15:47+03:00","message":"GetItemsByUserId: failed to scan rows"}
{"level":"error","module":"repository","error":"ERROR: syntax error at or near \"GROUP\" (SQLSTATE 42601)","time":"2025-02-15T12:16:19+03:00","message":"GetItemsByUserId: failed to scan rows"}
{"level":"error","module":"repository","error":"ERROR: syntax error at end of input (SQLSTATE 42601)","time":"2025-02-15T12:23:00+03:00","message":"GetItemsByUserId: failed to scan rows"}
{"level":"error","module":"repository","error":"ERROR: syntax error at or near \"GROUP\" (SQLSTATE 42601)","time":"2025-02-15T12:27:59+03:00","message":"GetItemsByUserId: failed to scan rows"}
{"level":"error","module":"repository","error":"ERROR: syntax error at or near \"GROUP\" (SQLSTATE 42601)","time":"2025-02-15T12:31:28+03:00","message":"GetItemsByUserId: failed to scan rows"}
{"level":"error","module":"repository","error":"ERROR: syntax error at end of input (SQLSTATE 42601)","time":"2025-02-15T12:52:54+03:00","message":"GetItemsByUserId: failed to scan rows"}
{"level":"error","module":"repository","error":"parsing slice destination: scany: destination must be a slice, got: *[]models.SendCoins","time":"2025-02-15T12:58:38+03:00","message":"SentCoinsByUserId: failed to scan rows"}
{"level":"error","module":"repository","error":"scanning: scanning: doing scan: scanFn: scany: column: 'username': no corresponding field found, or it's unexported in models.SendCoins","time":"2025-02-15T12:59:51+03:00","message":"SentCoinsByUserId: failed to scan rows"}
{"level":"error","module":"service","error":"crypto/bcrypt: hashedPassword is not the hash of the given password","time":"2025-02-15T13:29:40+03:00","message":"password mismatch"}
{"level":"error","module":"api","error":"crypto/bcrypt: hashedPassword is not the hash of the given password","time":"2025-02-15T13:29:40+03:00","message":"failed to auth user"}
